final List<String> PointGameWords = [
  'El/la mas deportista.',
  'El/la mas infiel.',
  'El/la mas fiel.',
  'El mas tincho.',
  'La mas milipili.',
  'El/la mas fantasma.',
  'El/la mas gobernado/a.',
  'El/la mas chamuyero/a.',
  'El/la mas drogadicto/a.',
  'El/la mas manija.',
  'El/la mas responsable.',
  'El/la mas estudioso.',
  'El/la mas borracho.',
  'El/la mas friky.',
  'El/la que mas quebró en su vida.',
  'El/la que mas fracasos amorosos tuvo.',
  'El/la mas celoso.',
  'El/la que estuvo con vos.',
  'El/la que mas rompió la cuarentena.',
  'El/la mas careta.',
  'El/la que mas dice que despues te pasa la plata y no te la pasa nunca.',
  'El/la mas kirchnerista.',
  'El/la mas technoso.',
  'El/la mas cachenguero.',
  'El/la que te gusta de esta ronda.',
  'El/la mas cheto/a.',
  'El/la que mas la hace larga para todo.',
  'El/la mas buitre.',
  'El/la mas chacal.',
  'El/la mas feminista.',
  'El/la mejor consejero/a'
];
