final List<String> RetoWords = [
  "Dejar que el resto del grupo envíe un MD a alguien de tu Instagram.",
  "Darle un pico a la persona de la derecha.",
  "Darle un pico a la persona de la izquierda.",
  "Hacer un fondo blanco de un trago.",
  "Llamar a tu ex.",
  "Dejar que otra persona te haga cosquillas e intentar no reírte.",
  "Tenes que deslizar tus historias de instagram hasta que alguien diga que pare, tenes que responder con cualquier cosa la historia que toco.",
  "Durante 10 min tenes que hablar con acento cordobés.",
  "Empezar a seguir en Instagram a alguien que no soportes.",
  "Llamar a tu 'crush' y decirle que te gusta.",
  "Poner la foto de perfil de uno de tus amigos durante toda la noche.",
  "Segun el porcentaje de tu bateria tenes que tomar un trago, ejemplo: si tenes 50% de bateria tenes que tomar la mitad del trago.",
  "Llamar a tu mamá o papá y decirles que van a ser abuelos.",
  "Tenes que simular como chamuyas en el boliche.",
  "Dale me gusta a una foto vieja de alguien que te guste.",
  "Te tienen que cantar el feliz cumpleaños en el boliche.",
  "tenes que darle un pico a todos los jugadores.",
  "Tus amigos te tienen que filmar haciendo algo que de cringe y subirlo a historias de instagram.",
  "Tomar un trago de alguna mezcla que haga el grupo.",
  "Le tenes que invitar un trago en el boliche al que tenes en la derecha.",
  "Manda un mensaje diciendo “Te amo” a tres personas.",
  "Llama a un lugar de comida, pedile empanadas y decile lo siguiente: quiero 2 de carne, 4 de choclo, 1 de carne, 2 de choclo, 9 de carne, 5 de choclo, 5 de choclo... y otra más de choclo.",
  "Canta una canción con la boca llena de agua.",
  "Sacate una selfie, subila a la historia de instagram y etiqueta a la primera persona que salga con la letra \"A\".",
  "Tenes que gemir tan fuerte como puedas.",
  "tenes que darle tu celular a otro jugador dejarlo enviar un mensaje a cualquiera de tus contactos.",
  "Dejar que la persona a tu derecha dibuje algo en tu cara.",
];
