final List<String> YoNuncaWords = [
  'he mentido a un amigo para evitar un mal mayor.',
  'he fingido estar en un videoclip cuando salgo de la ducha mientras pongo caras intensas en el espejo.',
  'he mirado el papel después de ir al baño.',
  'he hecho pis en una pileta.',
  'he robado algo.',
  'me he tirado un pedo y me he hecho el boludo/a.',
  'he sido sacado/a de un bar o boliche.',
  'me he accidentado al tratar de impresionar un chico o una chica que me gustara.',
  'me he desmayado.',
  'me he equivocado al mandar un audio por Whatsapp.',
  'he llorado durante una película de Pixar.',
  'he hecho trampa en un examen.',
  'he vomitado por estar demasiado/a borracho/a.',
  'he hecho bulling a alguien.',
  'me he quedado paralizado en una presentación en público.',
  'he fingido reírme de un chiste que no entendí.',
  'he llamado mamá a mi profesora.',
  'le he mentido a mis padres.',
  'he tenido un accidente serio teniendo sexo.',
  'he dicho un “te amo” sin sentirlo.',
  'he utilizado un juguete sexual.',
  'he rechazado un beso.',
  'he entrado a un sex shop.',
  'he fingido que me llamaban para escapar de una cita.',
  'me he enamorado de alguien a través de internet.',
  'he pensado que un personaje de dibujos animados fuera sexy.',
  'le he agarrado la mano a la persona equivocada.',
  'he mandado capturas de pantalla de mis conversaciones con otra persona solo para criticarla.',
  'he mandado un audio picante a mi madre por error.',
  'he hecho sexting.',
  'he mandado a alguien fotos nude o mi ‘pack’.',
  'he dado “like” por accidente a una foto de mi ex.',
  'me he chamuyado con el novio/a de un amigo/a',
  'he revisado el Whatsapp de mi novio.',
  'me he hecho fotos en ropa interior.',
  'he vuelto con mi ex.',
  'me he juntado con el/la ex de un amigo.',
  'he revisado a quién daba like mis exparejas.',
  'me han pillado teniendo sexo.',
  'he pillado a un amigo teniendo sexo.',
  'me he sentido sexualmente atraído por el padre o la madre de algún amigo o amiga.',
  'me he sentido atraído por alguien del mismo sexo.',
  'he tenido una fantasía erótica con alguien de la escuela.',
  'me he sentido atraído por alguien de este grupo.',
  'he fantaseado con mi mejor amigo.',
  'he tenido una relación abierta.',
  'he sido pillado masturbándome.',
  'he preferido no estar con mi pareja.',
  'he dicho el nombre de otra persona que no sea con quién esté teniendo sexo.',
  'he sido infiel.',
  'he tenido sexo con más de una persona a la vez.',
  'lo he hecho (o he querido hacerlo) en un sitio público.',
  'me he besado con un familiar.',
  'he tenido una aventura de una noche.',
  'me he despertado desnudo(a) en casa ajena.',
  'he fingido un orgasmo.',
  'me he grabado o tomado una foto teniendo sexo.',
  'he pensado en otra persona mientras tenia sexo con alguien.'
];
